server:
  port: 8084
  
spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: CUSTOMER-MANAGEMENT-SERVICE
          uri: lb://CUSTOMER-MANAGEMENT-SERVICE
          predicates:
          - Path=/customers/**
        
        - id: ACCOUNT-MANAGEMENT-SERVICE
          uri: lb://ACCOUNT-MANAGEMENT-SERVICE
          predicates:
          - Path=/accounts/**
  config:
    import: optional:configserver:http://localhost:8085
    

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      default-zone: http://localhost:8761/eureka
